### PR TITLE
#283 xip.io replacement

### PR DESCRIPTION
**Pull request by bacherfl**
Instead of hard-coding xip.io into the URL, we now check if a hostname for the ingressgateway is available (like it is on EKS). If not, we use <ingress-ip>.xip.io as a fallback. The resulting domain is stored in a configmap in the keptn namespace that will be used by other services to determine the correct hostname.

### CODE REVIEW

**Comment by robertjahn** [comment]
In my testing this line causes install to fail since there were no keptn pods to wait for.
https://github.com/keptn/installer/blob/feature/283/xip-replacement/scripts/setupIstio.sh#L24
....
snippet of keptnInstall.sh log file
....
No resources found.
[keptn|DEBUG] [2019-06-03 16:59:49] Retry: 10/12 - Wait 20s for pods to start in namespace keptn ...
No resources found.
[keptn|DEBUG] [2019-06-03 17:00:10] Retry: 11/12 - Wait 20s for pods to start in namespace keptn ...
No resources found.
[keptn|DEBUG] [2019-06-03 17:00:30] Retry: 12/12 - Wait 20s for pods to start in namespace keptn ...
[keptn|ERROR] [2019-06-03 17:00:50] Pods in namespace keptn are not running.
[keptn|ERROR] [2019-06-03 17:00:50] Installing Istio failed.
[keptn|ERROR] [2019-06-03 17:00:50] Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up.

**Comment by robertjahn** [comment]
I don't see scripts/updateDomain.sh being called from any other scripts.  Is this a standalone script or should it be called from a script such as setupKeptn.sh?

**Comment by bacherfl** [comment]
> I don't see scripts/updateDomain.sh being called from any other scripts. Is this a standalone script or should it be called from a script such as setupKeptn.sh?

This is a standalone script

**Comment by bacherfl** [comment]
> In my testing this line causes install to fail since there were no keptn pods to wait for.
> https://github.com/keptn/installer/blob/feature/283/xip-replacement/scripts/setupIstio.sh#L24
> ....
> snippet of keptnInstall.sh log file
> ....
> No resources found.
> [keptn|DEBUG] [2019-06-03 16:59:49] Retry: 10/12 - Wait 20s for pods to start in namespace keptn ...
> No resources found.
> [keptn|DEBUG] [2019-06-03 17:00:10] Retry: 11/12 - Wait 20s for pods to start in namespace keptn ...
> No resources found.
> [keptn|DEBUG] [2019-06-03 17:00:30] Retry: 12/12 - Wait 20s for pods to start in namespace keptn ...
> [keptn|ERROR] [2019-06-03 17:00:50] Pods in namespace keptn are not running.
> [keptn|ERROR] [2019-06-03 17:00:50] Installing Istio failed.
> [keptn|ERROR] [2019-06-03 17:00:50] Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up.

did you execute the script directly from your machine, or did you deploy the installer via the CLI?

**Comment by robertjahn** [comment]
I had run from machine, so is the intention of the remove pods command
above the waitfor to just have the nodes delete/restart? If yes to
reinitialize, then I maybe just add a comment to code for clarification.

**Comment by robertjahn** [comment]
Ok. I know this is development branch and this may just be temporary, but
maybe add a comment to code to say ignore or what script used for.

**Comment by johannes-b** [comment]
Regarding the problem at line: https://github.com/keptn/installer/blob/feature/283/xip-replacement/scripts/setupIstio.sh#L24

I assume that you don't deploy the container registry in your EKS cluster. Thus, can you comment out the line `wait_for_all_pods_in_namespace "keptn"`. The reason is that without container registry the keptn namespace is empty at this point of time in the installation process and the scripts stops there.

(FYI: we will remove the internal container registry going forward: https://github.com/keptn/keptn/issues/378)

**Pull request merged**
